name: Codecov

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.32.3
      - name: Create coverage files
        run: deno test --unstable --coverage=coverage/cov_profile test/
      - name: Generate lcov file
        run: deno coverage --lcov --output=coverage/cov.lcov coverage/cov_profile
      - name: Collect coverage
        uses: codecov/codecov-action@v1.0.10
        with:
          file: ./coverage/cov.lcov
